
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"resource/libs/lib.js",
	"bin-debug/lib/util/Dictionary.js",
	"bin-debug/game/cfg/InviteConfig.js",
	"bin-debug/game/cfg/PromotionConfig.js",
	"bin-debug/game/cfg/SignConfig.js",
	"bin-debug/lib/net/BaseCmd.js",
	"bin-debug/game/cmd/NetAcieveCmd.js",
	"bin-debug/game/cmd/NetActivityCmd.js",
	"bin-debug/game/cmd/NetCircleCmd.js",
	"bin-debug/game/cmd/NetDrawHeroCmd.js",
	"bin-debug/game/cmd/NetEnterCmd.js",
	"bin-debug/game/cmd/NetFightCmd.js",
	"bin-debug/game/cmd/NetHeroUpCmd.js",
	"bin-debug/game/cmd/NetKeepLiveCmd.js",
	"bin-debug/game/cmd/NetMailCmd.js",
	"bin-debug/game/cmd/NetMakeMoneyCmd.js",
	"bin-debug/game/cmd/NetMonsterInfoCmd.js",
	"bin-debug/game/cmd/NetOreCmd.js",
	"bin-debug/game/cmd/NetPropCmd.js",
	"bin-debug/game/cmd/NetShareCmd.js",
	"bin-debug/game/cmd/NetWeaponShopCmd.js",
	"bin-debug/lib/util/ExternalUtil.js",
	"bin-debug/lib/util/DataConfig.js",
	"bin-debug/game/Config.js",
	"bin-debug/game/controller/BattleController.js",
	"bin-debug/game/controller/BonusList.js",
	"bin-debug/game/controller/BonusType.js",
	"bin-debug/game/model/artifact/Artifact.js",
	"bin-debug/game/model/artifact/ArtifactConfigGroupItem.js",
	"bin-debug/game/model/artifact/ArtifactConfigItem.js",
	"bin-debug/game/model/buff/BuffConfig.js",
	"bin-debug/game/model/fight/FightDataModel.js",
	"bin-debug/game/model/fight/FightDropConfig.js",
	"bin-debug/game/model/fight/FightReportItem.js",
	"bin-debug/game/model/fight/FightRoleVO.js",
	"bin-debug/game/model/fight/StageConfig.js",
	"bin-debug/game/model/ModelDict.js",
	"bin-debug/game/model/role/HeroModel.js",
	"bin-debug/game/model/role/HeroVO.js",
	"bin-debug/game/model/role/MonsterVO.js",
	"bin-debug/game/model/role/RoleConfig.js",
	"bin-debug/game/model/skill/SkillConfig.js",
	"bin-debug/game/model/test/StageData.js",
	"bin-debug/game/URLConfig.js",
	"bin-debug/game/view/component/BattleView.js",
	"bin-debug/game/view/component/CoinShowPanel.js",
	"bin-debug/game/view/component/DropGold.js",
	"bin-debug/game/view/component/GreenButton.js",
	"bin-debug/game/view/component/GreenCoinButton.js",
	"bin-debug/game/view/component/HeroBase.js",
	"bin-debug/game/view/component/Hero.js",
	"bin-debug/game/view/component/LifeBar.js",
	"bin-debug/game/view/component/Monster.js",
	"bin-debug/game/view/component/ProgressBar.js",
	"bin-debug/game/view/component/RoleIcon.js",
	"bin-debug/game/view/component/SevenDayButton.js",
	"bin-debug/game/view/component/StarButton.js",
	"bin-debug/game/view/component/StarCountComp.js",
	"bin-debug/game/view/component/ToggleBtn.js",
	"bin-debug/game/view/component/WeaponIcon.js",
	"bin-debug/game/view/component/YellowBigBtn.js",
	"bin-debug/game/view/component/YellowCoinButton.js",
	"bin-debug/game/view/component/YellowTwoCoinBtn.js",
	"bin-debug/game/view/panel/ActiveDayInvite.js",
	"bin-debug/game/view/panel/ActiveFruit.js",
	"bin-debug/game/view/panel/ActiveFund.js",
	"bin-debug/game/view/panel/ActiveGift.js",
	"bin-debug/game/view/panel/ActiveLimitCost.js",
	"bin-debug/game/view/panel/ActiveLimitDraw.js",
	"bin-debug/game/view/panel/ActiveLimitFestival.js",
	"bin-debug/game/view/panel/ActiveLimitInvite.js",
	"bin-debug/game/view/panel/ActiveLimitOnePay.js",
	"bin-debug/lib/view/BasePanel.js",
	"bin-debug/game/view/panel/ActiveLimitPanel.js",
	"bin-debug/game/view/panel/ActiveLimitPVP.js",
	"bin-debug/game/view/panel/ActiveLimitRecharge.js",
	"bin-debug/game/view/panel/ActiveLimitWord.js",
	"bin-debug/game/view/panel/ActivePanel.js",
	"bin-debug/game/view/panel/ActivePrivilege.js",
	"bin-debug/game/view/panel/ActiveRichSign.js",
	"bin-debug/game/view/panel/ActiveSign.js",
	"bin-debug/game/view/panel/ActiveTree.js",
	"bin-debug/game/view/panel/AlertApplyPanel.js",
	"bin-debug/game/view/panel/ArtifactPanel.js",
	"bin-debug/game/view/panel/BonusPanel.js",
	"bin-debug/game/view/panel/CircleGoPanel.js",
	"bin-debug/game/view/panel/CircleGoSuccessPanel.js",
	"bin-debug/game/view/panel/CirclePanel.js",
	"bin-debug/game/view/panel/CircleSuccessPanel.js",
	"bin-debug/game/view/panel/CoinPanel.js",
	"bin-debug/game/view/panel/DailyAchievePanel.js",
	"bin-debug/game/view/panel/DeblockPanel.js",
	"bin-debug/game/view/panel/DeleteFriendPanel.js",
	"bin-debug/game/view/panel/DialPanel.js",
	"bin-debug/game/view/panel/FeedBackPanel.js",
	"bin-debug/game/view/panel/FightResultPanel.js",
	"bin-debug/game/view/panel/FirstRechargePanel.js",
	"bin-debug/game/view/panel/FriendAddUID.js",
	"bin-debug/game/view/panel/FriendApply.js",
	"bin-debug/game/view/panel/FriendFindInfo.js",
	"bin-debug/game/view/panel/FriendGetGift.js",
	"bin-debug/game/view/panel/FriendGiftPanel.js",
	"bin-debug/game/view/panel/FriendInvite.js",
	"bin-debug/game/view/panel/FriendMainPanel.js",
	"bin-debug/game/view/panel/FriendSendTogether.js",
	"bin-debug/game/view/panel/FriendShare.js",
	"bin-debug/game/view/panel/GuidePanel.js",
	"bin-debug/game/view/panel/HelpPanel.js",
	"bin-debug/game/view/panel/LoadExtraPanel.js",
	"bin-debug/game/view/panel/LoginPanel.js",
	"bin-debug/game/view/panel/MailInfoPanel.js",
	"bin-debug/game/view/panel/MailPanel.js",
	"bin-debug/game/view/panel/MenuPanel.js",
	"bin-debug/game/view/panel/MineCaveUpPanel.js",
	"bin-debug/game/view/panel/MineFormationPanel.js",
	"bin-debug/game/view/panel/MineInPanel.js",
	"bin-debug/game/view/panel/MineMainPanel.js",
	"bin-debug/game/view/panel/MoneyUnitPanel.js",
	"bin-debug/game/view/panel/NoticePanel.js",
	"bin-debug/game/view/panel/OfflinePanel.js",
	"bin-debug/game/view/panel/PrivilegePanel.js",
	"bin-debug/game/view/panel/PVPBeforePanel.js",
	"bin-debug/game/view/panel/PVPFormation.js",
	"bin-debug/game/view/panel/PVPHonor.js",
	"bin-debug/game/view/panel/PVPPanel.js",
	"bin-debug/game/view/panel/PVPRank.js",
	"bin-debug/game/view/panel/PVPReport.js",
	"bin-debug/game/view/panel/PVPRule.js",
	"bin-debug/game/view/panel/PVPShop.js",
	"bin-debug/game/view/panel/RankPanel.js",
	"bin-debug/game/view/panel/RoleChangePanel.js",
	"bin-debug/game/view/panel/RoleDetailsPanel.js",
	"bin-debug/game/view/panel/RoleDrawInfoPanel.js",
	"bin-debug/game/view/panel/RoleDrawPanel.js",
	"bin-debug/game/view/panel/RoleFormationPanel.js",
	"bin-debug/game/view/panel/RolePanel.js",
	"bin-debug/game/view/panel/RoleStarRise.js",
	"bin-debug/game/view/panel/RoleStrengthRestart.js",
	"bin-debug/game/view/panel/ScencePanel.js",
	"bin-debug/game/view/panel/scene/background/PVEBackGround.js",
	"bin-debug/game/view/panel/scene/background/PVEForeground.js",
	"bin-debug/game/view/panel/scene/background/PVEMiddleGround.js",
	"bin-debug/game/view/panel/scene/background/PVEProspect.js",
	"bin-debug/game/view/panel/scene/background/PVETransitionEff.js",
	"bin-debug/game/view/panel/scene/background/PVPBackGround.js",
	"bin-debug/game/view/panel/scene/BossFightPanel.js",
	"bin-debug/game/view/panel/scene/core/BattleCheck.js",
	"bin-debug/game/view/panel/scene/core/FightConst.js",
	"bin-debug/game/view/panel/scene/core/FightProcessGenerator.js",
	"bin-debug/game/view/panel/scene/core/FightResStrategy.js",
	"bin-debug/game/view/panel/scene/core/FightRoleFactory.js",
	"bin-debug/game/view/panel/scene/core/FightUtils.js",
	"bin-debug/game/view/panel/scene/core/PriorityImage.js",
	"bin-debug/game/view/panel/scene/effect/BaseMCEffect.js",
	"bin-debug/game/view/panel/scene/effect/BattleStartEff.js",
	"bin-debug/game/view/panel/scene/effect/BloodWarnEff.js",
	"bin-debug/game/view/panel/scene/effect/BossIncomingEff.js",
	"bin-debug/game/view/panel/scene/effect/BuddhaPalmEff.js",
	"bin-debug/game/view/panel/scene/effect/FightWarnEff.js",
	"bin-debug/game/view/panel/scene/effect/FontEff.js",
	"bin-debug/game/view/panel/scene/effect/MCEff.js",
	"bin-debug/game/view/panel/scene/effect/MoveDustEff.js",
	"bin-debug/game/view/panel/scene/effect/NewChapterEff.js",
	"bin-debug/game/view/panel/scene/effect/PVEFailEff.js",
	"bin-debug/game/view/panel/scene/effect/RoleDieEff.js",
	"bin-debug/game/view/panel/scene/effect/RoleSkillEff.js",
	"bin-debug/game/view/panel/scene/effect/ShakeScreenEff.js",
	"bin-debug/game/view/panel/scene/effect/SkillNameEff.js",
	"bin-debug/game/view/panel/scene/PVEFightContainer.js",
	"bin-debug/game/view/panel/scene/PVPFightPanel.js",
	"bin-debug/game/view/panel/scene/view/BossStageProgress.js",
	"bin-debug/game/view/panel/scene/view/DropItem.js",
	"bin-debug/game/view/panel/scene/view/FightContainer.js",
	"bin-debug/game/view/panel/scene/view/FightRole.js",
	"bin-debug/game/view/panel/scene/view/PlayerHead.js",
	"bin-debug/game/view/panel/scene/view/RoleBody.js",
	"bin-debug/game/view/panel/scene/view/RoleHPBar.js",
	"bin-debug/game/view/panel/scene/view/RoundProgress.js",
	"bin-debug/game/view/panel/scene/view/StageProgress.js",
	"bin-debug/game/view/panel/SecretAreaPanel.js",
	"bin-debug/game/view/panel/SecretPanel.js",
	"bin-debug/game/view/panel/SettingHeadPanel.js",
	"bin-debug/game/view/panel/SettingPanel.js",
	"bin-debug/game/view/panel/SevenDayPanel.js",
	"bin-debug/game/view/panel/ShopPanel.js",
	"bin-debug/game/view/panel/ShowItemTipPanel.js",
	"bin-debug/game/view/panel/SmallMonsterCatch.js",
	"bin-debug/game/view/panel/SmallMonsterInfo.js",
	"bin-debug/game/view/panel/SmallMonsterPanel.js",
	"bin-debug/game/view/panel/TargetPanel.js",
	"bin-debug/game/view/panel/TopPanel.js",
	"bin-debug/game/view/panel/WeaponBuyPanel.js",
	"bin-debug/game/view/panel/WeaponInfoPanel.js",
	"bin-debug/game/view/panel/WeaponPanel.js",
	"bin-debug/game/view/panel/XunShanPanel.js",
	"bin-debug/game/view/renderer/ActDayInviteRenderer.js",
	"bin-debug/game/view/renderer/ActFundRenderer.js",
	"bin-debug/game/view/renderer/ActLimitDrawRenderer.js",
	"bin-debug/game/view/renderer/ActLimitRechargeRenderer.js",
	"bin-debug/game/view/renderer/ActLimitWordRenderer.js",
	"bin-debug/game/view/renderer/DailyAchieveRenderer.js",
	"bin-debug/game/view/renderer/FriendApplyRenderer.js",
	"bin-debug/game/view/renderer/FriendGetGiftRenderer.js",
	"bin-debug/game/view/renderer/FriendInviteRenderer.js",
	"bin-debug/game/view/renderer/FriendSendTogetherRenderer.js",
	"bin-debug/game/view/renderer/MailRenderer.js",
	"bin-debug/game/view/renderer/MineInRenderer.js",
	"bin-debug/game/view/renderer/MineInRoleRenderer.js",
	"bin-debug/game/view/renderer/MoneyUnitRenderer.js",
	"bin-debug/game/view/renderer/MonsterCatchRenderer.js",
	"bin-debug/game/view/renderer/MonsterRenderer.js",
	"bin-debug/game/view/renderer/PVPHonorRenderer.js",
	"bin-debug/game/view/renderer/PVPRankRenderer.js",
	"bin-debug/game/view/renderer/PVPShopRenderer.js",
	"bin-debug/game/view/renderer/RankRenderer.js",
	"bin-debug/game/view/renderer/RoleBuffRenderer.js",
	"bin-debug/game/view/renderer/RoleChangeRenderer.js",
	"bin-debug/game/view/renderer/RoleFormationRenderer.js",
	"bin-debug/game/view/renderer/RoleRenderer.js",
	"bin-debug/game/view/renderer/RoleShipRenderer.js",
	"bin-debug/game/view/renderer/RoleSkillRenderer.js",
	"bin-debug/game/view/renderer/SecretAreaRenderer.js",
	"bin-debug/game/view/renderer/SecretRenderer.js",
	"bin-debug/game/view/renderer/SettingHeadRenderer.js",
	"bin-debug/game/view/renderer/SevenDayRenderer.js",
	"bin-debug/game/view/renderer/ShopItemRenderer.js",
	"bin-debug/game/view/renderer/WeaponBuyRenderer.js",
	"bin-debug/game/view/renderer/WeaponRenderer.js",
	"bin-debug/game/view/renderer/WeaponSuitRenderer.js",
	"bin-debug/game/view/renderer/XunShanRenderer.js",
	"bin-debug/lib/CmdID.js",
	"bin-debug/lib/ContextEvent.js",
	"bin-debug/lib/engine/AssetAdapter.js",
	"bin-debug/lib/engine/ThemeAdapter.js",
	"bin-debug/lib/Global.js",
	"bin-debug/lib/manager/EventManager.js",
	"bin-debug/lib/manager/PanelManager.js",
	"bin-debug/lib/net/Http.js",
	"bin-debug/lib/sound/BaseSound.js",
	"bin-debug/lib/sound/SoundManager.js",
	"bin-debug/lib/UserMethod.js",
	"bin-debug/lib/UserProxy.js",
	"bin-debug/lib/util/ArrayUtil.js",
	"bin-debug/lib/util/AutoBitmap.js",
	"bin-debug/lib/util/BaseTicker.js",
	"bin-debug/lib/util/BigNum.js",
	"bin-debug/lib/util/BitUtil.js",
	"bin-debug/lib/util/ColorFilter.js",
	"bin-debug/lib/util/DisplayUtil.js",
	"bin-debug/lib/util/EffectUtil.js",
	"bin-debug/lib/util/GeomUtil.js",
	"bin-debug/lib/util/ImageLoader.js",
	"bin-debug/lib/util/LoaderUtils.js",
	"bin-debug/lib/util/MathUtil.js",
	"bin-debug/lib/util/McUtil.js",
	"bin-debug/lib/util/MovieClipUtils.js",
	"bin-debug/lib/util/ObjectPool.js",
	"bin-debug/lib/util/share/BaseShareType.js",
	"bin-debug/lib/util/share/imples/ShareFKType.js",
	"bin-debug/lib/util/share/imples/ShareType.js",
	"bin-debug/lib/util/share/ShareUtils.js",
	"bin-debug/lib/util/ShareUtil.js",
	"bin-debug/lib/util/SoundUils.js",
	"bin-debug/lib/util/StringUtil.js",
	"bin-debug/lib/util/TDGAUtil.js",
	"bin-debug/lib/util/TickerUtil.js",
	"bin-debug/lib/util/TimeUtil.js",
	"bin-debug/lib/util/TipsUtils.js",
	"bin-debug/lib/view/Alert.js",
	"bin-debug/lib/view/Broadcast.js",
	"bin-debug/lib/view/CheckBox.js",
	"bin-debug/lib/view/LoadingUI.js",
	"bin-debug/lib/view/LoadPanel.js",
	"bin-debug/lib/view/Notice.js",
	"bin-debug/lib/view/PagePoint.js",
	"bin-debug/lib/view/Processing.js",
	"bin-debug/lib/view/QuickAlert.js",
	"bin-debug/lib/view/RedPoint.js",
	"bin-debug/lib/view/SimpleButton.js",
	"bin-debug/lib/view/SimpleGroup.js",
	"bin-debug/lib/view/TabButton.js",
	"bin-debug/lib/view/Tips.js",
	"bin-debug/Main.js",
	//----auto game_file_list end----
];

var window = {};

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "fixedWidth",
		contentWidth: 480,
		contentHeight: 800,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:30,textColor:0x00c200,bgAlpha:0.5",
		showLog: false,
		logFilter: "",
		maxTouches: 1,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};